{% set name = "jsonpath-rw" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsonpath-rw-{{ version }}.tar.gz
  sha256: 05c471281c45ae113f6103d1268ec7a4831a2e96aa80de45edc89b11fac4fbec

build:
  entry_points:
    - jsonpath = jsonpath_rw.bin.jsonpath:entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ply
    - decorator
    - six

test:
  imports:
    - jsonpath_rw
  commands:
    - pip check
    - jsonpath --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kennknowles/python-jsonpath-rw
  summary: A robust and significantly extended implementation of JSONPath for Python, with a clear AST for metaprogramming.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
